import { defineConfig } from "vitest/config";

// NumPy differential tests (PLAN §63). Cases are generated by
// python/generators/generate_cases.py; run via `pnpm test:diff`.
export default defineConfig({
  test: {
    include: ["tests/differential/**/*.test.ts"],
    pool: "forks",
  },
});
